[[ define "location" ]]
  [[ template "region" . ]]
  [[ template "plugin_namespace" . ]]
  datacenters = [[ var "datacenters" . | toJson ]]
  node_pool   = [[ var "node_pool" . | quote ]]
[[- end -]]
