[[- define "job_name" -]]
[[- if eq .prometheus_consul_exporter.job_name "" -]]
[[- .nomad_pack.pack.name | quote -]]
[[- else -]]
[[- .prometheus_consul_exporter.job_name | quote -]]
[[- end -]]
[[- end -]]
