name: Notify Integration Release
on:
  push:
    paths:
      - "packs/**"
    branches:
      - main
jobs:
  determine_identifiers:
    name: Determine Identifiers
    runs-on: ubuntu-latest
    outputs:
      identifiers: ${{ steps.output_result.outputs.identifiers }}
    steps:
      - name: Checkout Nomad Pack Community Registry
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - id: determine_changed_files
        name: Determine Changed Files
        uses: tj-actions/changed-files@ec1e14cf27f4585783f463070881b2c499349a8a # v37.0.3
      - id: output_result
        run: |
          matrixArray=$(
            echo ${{ steps.determine_changed_files.outputs.all }} \
              | sed 's/ /\n/g' \
              | ./.github/scripts/files-to-identifiers.sh \
              | jq --raw-input --slurp  'split("\n") | map(select(. != ""))' \
              | jq -c .
          )
          echo "identifiers=$matrixArray" >> "$GITHUB_OUTPUT"

  notify_release:
    runs-on: ubuntu-latest
    needs: determine_identifiers
    strategy:
      matrix:
        integration_identifier: ${{fromJson(needs.determine_identifiers.outputs.identifiers)}}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - id: calculate_version
        name: Calculate Version
        run: |
          version="$(./.github/scripts/version-from-identifier.sh ${{ matrix.integration_identifier }})"
          echo "Computed Version: $version"
          echo "releaseVersion=$version" >> "$GITHUB_OUTPUT"
      - name: Checkout integration-release-action
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          repository: hashicorp/integration-release-action
          path: ./integration-release-action
      - name: Notify Release
        uses: ./integration-release-action
        with:
          integration_identifier: ${{ matrix.integration_identifier }}
          release_version: ${{ steps.calculate_version.outputs.releaseVersion }}
          release_sha: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          integration_strategy: 'nomad-pack'
