[[- define "full_job_name" -]]
[[- if eq (var "job_name" .) "" -]]
[[- meta "pack.name" . | quote -]]
[[- else -]]
[[- var "job_name" . | quote -]]
[[- end -]]
[[- end -]]

[[- define "full_args" -]]
[[- $fullArgs := prepend (var "autoscaler_agent_task.additional_cli_args" .) "agent" -]]
[[- if var "autoscaler_agent_task.scaling_policy_files" . ]][[ $fullArgs = append $fullArgs "-policy-dir=${NOMAD_TASK_DIR}/policies" ]][[- end -]]
[[- if var "autoscaler_agent_task.config_files" . ]][[ $fullArgs = append $fullArgs "-config=${NOMAD_TASK_DIR}/config" ]][[- end -]]
[[ $fullArgs | toPrettyJson ]]
[[- end -]]
